### ISSUE TITLE
SSRFSourceCheck的addSourceType方法只会返回false

### ISSUE THREAD

**Issue by mdkk** [HXSecurity/DongTai-agent-java#522]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.9.1

### Installation Type

Official Docker Compose

### Service Name

DongTai-agent-java

### Describe the details of the bug and the steps to reproduce it

有个小问题，java-agent中SSRFSourceCheck的addSourceType方法里checkTaintPool的污点查找结果为什么没有体现到返回值里，这个函数只会返回false

**Comment by lostsnow** [comment]
During the process of detecting SSRF vulnerabilities, outgoing HTTP requests are dissected to determine the propagation of tainted data across individual components such as protocol, domain name, and path, instead of relying solely on a single return value. Furthermore, SSRF vulnerabilities are generally only exploitable when the protocol and domain name are controllable. Therefore, the specific location of tainted data within the URL will be marked, and the server will conduct the corresponding detection and handling.

**Comment by mdkk** [comment]
ok, thanks!

**Comment by mdkk** [comment]
还有一个问题, 在 DynamicPropagatorScanner scan 函数里
boolean hit = sinkSourceHitTaintPool(event, sinkNode);
        if (serviceCall || hit) 
由于SSRFSourceCheck addSourceType方法只会返回false, 如果ssrf发起的不是http请求(如ftp或其它请求), TRACK_MAP 就不会记录 methodEvent,

**Comment by lostsnow** [comment]
Yes, currently SSRF detection is only performed on requests using the HTTP(S) protocol
